name: Post Nigerian News

on:
  schedule:
    - cron: '0 8 * * *'  # 8 AM UTC = 4 AM EDT
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the news bot
        run: python bot.py
      
beautifulsoup4>=4.12.3
tweepy>=4.14.0
python-dotenv>=1.0.1
schedule>=1.2.1


